apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: adev-pr
  labels:
    app.kubernetes.io/name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: orbit-d-external-dns@prj-83923-d-orbit-8092.iam.gserviceaccount.com

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-adev
  labels:
    app.kubernetes.io/name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods","nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer-adev
  labels:
    app.kubernetes.io/name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-adev
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: adev-pr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: adev-pr
  labels:
    app.kubernetes.io/name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: us-docker.pkg.dev/prj-83923-s-artifact-3736/orbit-s-repo/external-dns:v1.0
          args:
            - --namespace=adev-pr
            - --source=service
            - --source=ingress
            - --domain-filter=adev.sigbankdd.com
            - --provider=google
            - --google-zone-visibility=public
            - --registry=txt
            - --txt-owner-id=adev-signbankdd-com
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - NET_RAW
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
